name: gosql
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13, 1.14, 1.15, 1.16]
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 32574:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Golang ${{ matrix.go-version }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Init Database
        run: |
          mysql -h127.0.0.1 --port 32574 -uroot -proot -e 'CREATE DATABASE IF NOT EXISTS db1;'
          mysql -h127.0.0.1 --port 32574 -uroot -proot -e 'CREATE DATABASE IF NOT EXISTS db2;'

      - name: Test
        env:
          MYSQL_TEST_DSN1: "root:root@tcp(127.0.0.1:32574)/db1?parseTime=true"
          MYSQL_TEST_DSN2: "root:root@tcp(127.0.0.1:32574)/db2?parseTime=true"
        run: |
          go get && make test
          bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN}}
